# Generated by Django 4.1.7 on 2023-02-16 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('blk_or_lot', models.IntegerField(blank=True, null=True)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street_name', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('municipality_or_city', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField()),
                ('label', models.CharField(max_length=100)),
                ('coordinates_x', models.CharField(max_length=100)),
                ('coordinates_y', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
